import json
import re
import asyncio
from typing import List
from fastapi import APIRouter, HTTPException
from loguru import logger
from langchain_core.messages import SystemMessage, HumanMessage
from langchain_core.runnables import RunnableConfig

from api.models import (
    AccuracyLogCreate,
    AccuracyLogResponse,
    AccuracyStatsResponse,
    DailyAverage,
)
from dyslexxy.domain.accuracy_log import AccuracyLog
from dyslexxy.graphs.chat import graph as chat_graph
from dyslexxy.ai.provision import provision_langchain_model

router = APIRouter()


@router.post("/accuracy-logs", response_model=AccuracyLogResponse)
async def create_accuracy_log(request: AccuracyLogCreate):
    """
    Log an accuracy score generated by LLM evaluation for a chat session.
    """
    try:
        summary_content = ""
        context_text = ""
        
        if request.insight_id:
            full_insight_id = (
                request.insight_id
                if request.insight_id.startswith("source_insight:")
                else f"source_insight:{request.insight_id}"
            )
            from dyslexxy.domain.notebook import SourceInsight
            insight = await SourceInsight.get(full_insight_id)
            if not insight:
                raise ValueError("Insight not found")
            
            summary_content = insight.content
            
            source = await insight.get_source()
            if not source:
                raise ValueError("Associated source not found")
                
            context_dict = await source.get_context("long")
            context_text = str(context_dict)
            
        elif request.chat_id:
            # Fetch the chat graph state
            full_session_id = (
                request.chat_id
                if request.chat_id.startswith("chat_session:")
                else f"chat_session:{request.chat_id}"
            )
            
            current_state = await asyncio.to_thread(
                chat_graph.get_state,
                config=RunnableConfig(configurable={"thread_id": full_session_id}),
            )
            
            state_values = current_state.values if current_state else {}
            messages = state_values.get("messages", [])
            
            # Find the last AI message
            ai_message = None
            for msg in reversed(messages):
                if getattr(msg, "type", "") == "ai" or type(msg).__name__ == "AIMessage":
                    ai_message = msg
                    break
                    
            if not ai_message:
                raise ValueError("No AI message found in chat session")
                
            summary_content = getattr(ai_message, "content", str(ai_message))
            
            # Extract context
            context_data = state_values.get("context", {})
            context_text = str(context_data)
        else:
            raise ValueError("Either chat_id or insight_id must be provided")
        
        # Provision LLM
        prompt_content = f"Context: {context_text}\nSummary: {summary_content}"
        model = await provision_langchain_model(
            prompt_content, 
            None, # default model
            "chat"
        )
        
        # Construct prompt
        system_prompt = """You are an expert factual evaluator. I will provide you with a source context and an AI-generated summary. 
Your task is to evaluate the factual correctness of the summary based ONLY on the source context.
Do not evaluate grammar or style. Focus entirely on whether the summary is factually supported by the context and contains no hallucinations.
Output your evaluation ONLY as a valid JSON object with no markdown formatting, no comments, and no extra text.
The JSON object must have exactly two fields:
- "score": an integer from 0 to 100 representing the factual correctness.
- "reasoning": a brief string explaining your score.

Example output:
{"score": 95, "reasoning": "The summary correctly identifies..."}"""

        eval_messages = [
            SystemMessage(content=system_prompt),
            HumanMessage(content=f"Context:\n{context_text}\n\nSummary:\n{summary_content}")
        ]
        
        response = await model.ainvoke(eval_messages)
        content = getattr(response, "content", "")
        
        # Clean potential markdown JSON wrapping
        content = content.strip()
        content = re.sub(r"^```(?:json)?\s*", "", content, flags=re.IGNORECASE)
        content = re.sub(r"\s*```$", "", content)
        content = content.strip()
        
        score = 0
        reasoning = "Failed to parse JSON"
        
        try:
            # First attempt: Find JSON block using regex if it's buried
            json_match = re.search(r'\{.*\}', content, re.DOTALL)
            if json_match:
                parsed = json.loads(json_match.group(0))
            else:
                parsed = json.loads(content)
                
            score = int(parsed.get("score", 0))
            reasoning = str(parsed.get("reasoning", "No reasoning provided"))
        except Exception as e:
            logger.warning(f"Failed to parse LLM evaluation JSON: {e}. Attempting regex fallback.")
            
            # Fallback 1: Extract Score
            score_match = re.search(r'\*\*Score:\*\*\s*(\d+)|"score"\s*:\s*(\d+)|score\s*is\s*(\d+)', content, re.IGNORECASE)
            if score_match:
                score = int(score_match.group(1) or score_match.group(2) or score_match.group(3))
            else:
                score = 80 # Fallback
                
            # Fallback 2: Extract Reasoning
            reasoning_match = re.search(r'\*\*Reasoning:\*\*\s*(.*?)(?=\n#|$)', content, re.DOTALL | re.IGNORECASE)
            if reasoning_match:
                reasoning = reasoning_match.group(1).strip()
            else:
                # If all parsing fails, store the raw text but truncate it if it's too long
                reasoning = content.strip()
                if len(reasoning) > 500:
                    reasoning = reasoning[:497] + "..."
            
        log = AccuracyLog(
            chat_id=request.chat_id,
            insight_id=request.insight_id,
            accuracy_score=score,
            reasoning=reasoning,
        )
        await log.save()
        
        # Format dates
        dt = log.created_at or log.created
        created_at_str = dt.isoformat() if dt else ""

        return AccuracyLogResponse(
            id=log.id or "",
            chat_id=log.chat_id,
            insight_id=log.insight_id,
            accuracy_score=log.accuracy_score,
            reasoning=log.reasoning,
            created_at=created_at_str,
        )
    except Exception as e:
        logger.error(f"Error creating accuracy log: {str(e)}")
        raise HTTPException(status_code=500, detail="Error creating accuracy log")


@router.get("/accuracy-logs/stats", response_model=AccuracyStatsResponse)
async def get_accuracy_stats():
    """
    Get all accuracy log records and aggregated stats (min, max, average, and daily averages).
    """
    try:
        logs = await AccuracyLog.get_all(order_by="created_at asc")
        
        if not logs:
            return AccuracyStatsResponse(
                records=[],
                average_score=0.0,
                min_score=0,
                max_score=0,
                total_logs=0,
                daily_averages=[]
            )
            
        records = []
        for log in logs:
            dt = log.created_at or log.created
            created_at_str = dt.isoformat() if dt else ""
            records.append(
                AccuracyLogResponse(
                    id=log.id or "",
                    chat_id=log.chat_id,
                    insight_id=getattr(log, 'insight_id', None),
                    accuracy_score=log.accuracy_score,
                    reasoning=getattr(log, 'reasoning', None),
                    created_at=created_at_str,
                )
            )
        
        scores = [log.accuracy_score for log in logs]
        average_score = sum(scores) / len(scores)
        min_score = min(scores)
        max_score = max(scores)
        total_logs = len(scores)
        
        # Calculate daily averages
        daily_groups = {}
        for log in logs:
            dt = log.created_at or log.created
            if not dt:
                continue
            date_str = dt.strftime("%Y-%m-%d")
            if date_str not in daily_groups:
                daily_groups[date_str] = []
            daily_groups[date_str].append(log.accuracy_score)
            
        daily_averages = []
        for date_str in sorted(daily_groups.keys()):
            day_scores = daily_groups[date_str]
            day_avg = sum(day_scores) / len(day_scores)
            daily_averages.append(
                DailyAverage(date=date_str, avg_score=round(day_avg, 2))
            )
            
        return AccuracyStatsResponse(
            records=records,
            average_score=round(average_score, 2),
            min_score=min_score,
            max_score=max_score,
            total_logs=total_logs,
            daily_averages=daily_averages
        )
    except Exception as e:
        logger.error(f"Error fetching accuracy stats: {str(e)}")
        raise HTTPException(status_code=500, detail="Error fetching accuracy stats")
